Add infinite loader
Chartisan/Chartisan pull request #13
Opened 2020-11-17 19:21 UTC by pedroroccon

New option for loader: infinite.

You can replace the default loader in your chart:

```javascript
const chart = new Chartisan({
        el: '#chart-fluxo-caixa',
        url: "", 
	loader: {
		type: 'infinite',
		size: [35, 35],
		color: '#000',
		text: 'Loading with infinite',
		textColor: '#000',
	}
});
```

2020-11-18 00:39 UTC, ConsoleTVs commented
You did not add it to the loaders... https://github.com/Chartisan/Chartisan/blob/master/src/loader/index.ts#L41

2020-11-18 00:40 UTC, ConsoleTVs requested changes
The loader needs to be added to the loaders object.

2020-11-18 11:20 UTC, pedroroccon commented
> The loader needs to be added to the loaders object.

Added!

2020-11-18 11:53 UTC, pedroroccon commented
> The loader needs to be added to the loaders object.

Added!

2020-11-20 18:18 UTC, ConsoleTVs commented
Also, (this wont happen in the future) but you'll also need to add it to the loader type:

https://github.com/Chartisan/Chartisan/blob/c9b48a0bd206507ab3b2550ae3032c713827b602/src/loader/index.ts#L7

Simply put 'bar' | 'infinite'

2020-11-20 20:40 UTC, pedroroccon commented
> 'bar' | 'infinite'

Added! Also, i fixed the formatting (when i saved, it auto formats)

2020-11-20 22:52 UTC, merged

2020-11-20 22:52 UTC, ConsoleTVs commented
Looks good :)